aapi.o: aapi.c astr.h aobj.h adef.h aarch.h alo.h aaux.h atuple.h alist.h \
 atable.h afun.h aenv.h actx.h actx.x64.win.h agc.h agbl.h avm.h aparse.h \
 alex.h aio.h abuf.h amem.h adump.h aapi.h
aaux.o: aaux.c adef.h aarch.h alo.h aaux.h
abaselib.o: abaselib.c atuple.h aobj.h adef.h aarch.h alo.h aaux.h \
 alist.h atable.h agc.h agbl.h astr.h afun.h aenv.h aapi.h abaselib.h
abuf.o: abuf.c abuf.h amem.h aobj.h adef.h aarch.h alo.h aaux.h
acode.o: acode.c abc.h adef.h aarch.h alo.h aaux.h afun.h aobj.h aenv.h \
 astr.h aop.h aerr.h agc.h agbl.h afmt.h abuf.h amem.h astrx.h alex.h \
 aio.h acode.h aparse.h
adbg.o: adbg.c adbg.h adef.h aarch.h alo.h aaux.h
adump.o: adump.c abc.h adef.h aarch.h alo.h aaux.h afun.h aobj.h aenv.h \
 astr.h agc.h agbl.h adump.h
aenv.o: aenv.c abc.h adef.h aarch.h alo.h aaux.h astr.h aobj.h atuple.h \
 alist.h actx.h actx.x64.win.h aenv.h amem.h agc.h agbl.h afun.h aerr.h \
 astrx.h alex.h aio.h abuf.h
aerr.o: aerr.c astr.h aobj.h adef.h aarch.h alo.h aaux.h aenv.h agc.h \
 agbl.h afun.h avm.h aerr.h
afmt.o: afmt.c afmt.h abuf.h amem.h aobj.h adef.h aarch.h alo.h aaux.h \
 astr.h
afun.o: afun.c amem.h aobj.h adef.h aarch.h alo.h aaux.h agc.h agbl.h \
 astr.h afun.h aenv.h
agc.o: agc.c agc.h agbl.h astr.h aobj.h adef.h aarch.h alo.h aaux.h \
 afun.h aenv.h
aio.o: aio.c amem.h aobj.h adef.h aarch.h alo.h aaux.h agc.h agbl.h \
 astr.h afun.h aenv.h aio.h
alex.o: alex.c aenv.h astr.h aobj.h adef.h aarch.h alo.h aaux.h aerr.h \
 acode.h aparse.h agc.h agbl.h afun.h alex.h aio.h abuf.h amem.h astrx.h \
 afmt.h
alist.o: alist.c amem.h aobj.h adef.h aarch.h alo.h aaux.h agc.h agbl.h \
 astr.h afun.h aenv.h alist.h
alo.o: alo.c alist.h aobj.h adef.h aarch.h alo.h aaux.h aerr.h aparse.h \
 agc.h agbl.h astr.h afun.h aenv.h alex.h aio.h abuf.h amem.h adump.h \
 aapi.h abaselib.h
aload.o: aload.c aio.h astr.h aobj.h adef.h aarch.h alo.h aaux.h aenv.h \
 amem.h agc.h agbl.h afun.h aload.h
amem.o: amem.c aenv.h astr.h aobj.h adef.h aarch.h alo.h aaux.h agc.h \
 agbl.h afun.h aerr.h amem.h
aop.o: aop.c aop.h adef.h aarch.h alo.h aaux.h aerr.h aobj.h
aparse.o: aparse.c afun.h aobj.h adef.h aarch.h alo.h aaux.h aenv.h \
 astr.h aerr.h acode.h aparse.h agc.h agbl.h alex.h aio.h abuf.h amem.h
asave.o: asave.c aio.h astr.h aobj.h adef.h aarch.h alo.h aaux.h aenv.h \
 agc.h agbl.h afun.h aload.h
astr.o: astr.c aenv.h astr.h aobj.h adef.h aarch.h alo.h aaux.h amem.h \
 agc.h agbl.h afun.h astrx.h alex.h aio.h abuf.h
astrx.o: astrx.c astr.h aobj.h adef.h aarch.h alo.h aaux.h astrx.h alex.h \
 aio.h abuf.h amem.h
atable.o: atable.c astr.h aobj.h adef.h aarch.h alo.h aaux.h amem.h agc.h \
 agbl.h afun.h aenv.h atable.h
atuple.o: atuple.c amem.h aobj.h adef.h aarch.h alo.h aaux.h agc.h agbl.h \
 astr.h afun.h aenv.h atuple.h
avm.o: avm.c abc.h adef.h aarch.h alo.h aaux.h afun.h aobj.h aenv.h \
 astr.h amem.h agc.h agbl.h aapi.h avm.h
